### ISSUE TITLE
License information is missing or well-hidden.

### ISSUE THREAD

**Issue by apotheon** [DecentralizeJustice/anonymousLocker#5]
Please provide a LICENSE file or license text in the README file, or at least insert an [SPDX](https://spdx.org/licenses/) license identifier string (e.g. COIL-1.0 for the [Copyfree Open Innovation License](https://spdx.org/licenses/COIL-1.0.html)) in the package.json file.

If your license choice is any of the [certified copyfree licenses](https://copyfree.org/standard/licenses), this project can also be added to the [copyfree works list](https://copyfree.org/resources/works).

**Comment by itsMikeLowrey** [comment]
Added the MIT License to the readme.

**Comment by apotheon** [comment]
Thank you!  I'll add the project to the queue for inclusion in the CI works list.
