### ISSUE TITLE
Future expansion of AnonShopApp

### ISSUE THREAD

**Issue by aclifton314** [DecentralizeJustice/anonymousLocker#8]
Hi Donely,

I didn't know the best way to contact you so I opened up an issue here. Feel free to close it at your convenience.

I wanted to toss around an idea with you about a possible future expansion of AnonShopApp that could maintain anonymity at the point of pickup and allow for purchases to be made through ecommerce sites outside of amazon. I know you're likely busy developing AnonShopApp right now, so no big rush. If you're interested in discussing it, feel free to hit me up.

**Comment by itsMikeLowrey** [comment]
Responded!
